apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odh-deployment
spec:
  destination:
    namespace: odh-deployment
    name: dev-cluster
  project: default
  source:
    path: odh-operator-kfdef
    repoURL: https://github.com/martinpovolny/odh.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
