apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odh-operator
spec:
  destination:
    namespace: odh-operator
    name: in-cluster
  project: default
  source:
    path: odh/base/operator
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
